### ISSUE TITLE
Enable Adaptive Replica Selection

### ISSUE THREAD

**Issue by missinglink** [pelias/terraform-elasticsearch#15]
[This Article](https://www.elastic.co/blog/improving-response-latency-in-elasticsearch-with-adaptive-replica-selection) mentions a setting named `cluster.routing.use_adaptive_replica_selection` which may reduce latency by sending queries to replicas which are less busy, rather than simply round-robin-ing them.

> ARS is available in Elasticsearch 6.1 and later, but is turned off by default in all 6.x releases. It can be turned on dynamically by changing the cluster.routing.use_adaptive_replica_selection setting:

> note: this setting is [enabled by default in ES7](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_adaptive_replica_selection_enabled_by_default_2)

```bash
PUT /_cluster/settings
{
  "transient": {
    "cluster.routing.use_adaptive_replica_selection": true
  }
}
```

**Comment by orangejulius** [comment]
We only support ES7 in this project now, so we should be getting this for free :)
