### ISSUE TITLE
Can't run "cloud_init" configuration

### ISSUE THREAD

**Issue by KristinaHus** [pelias/terraform-elasticsearch#21]
**Describe the bug**
I'm trying to set up the recommended terraform-elasticsearch. But it doesn't run the setup script correctly. 
That's what I see when I open EC2 instance logs

`ip-10-0-0-199 login: [  318.790498] cloud-init[1144]: Connect timeout on endpoint URL: "https://autoscaling.us-west-2.amazonaws.com/"
[  318.838634] cloud-init[1144]: Cloud-init v. 20.2-45-g5f7825e2-0ubuntu1~18.04.1 running 'modules:final' at Wed, 09 Sep 2020 07:13:34 +0000. Up 14.26 seconds.
[  318.841730] cloud-init[1144]: 2020-09-09 07:18:38,918 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [255]
[  318.846117] cloud-init[1144]: s3_bucket not set, no snapshot will be loaded
[  318.848149] cloud-init[1144]: 2020-09-09 07:18:38,926 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
[  318.851800] cloud-init[1144]: 2020-09-09 07:18:38,927 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
`
The instant is running and all checks are passed, but it is not reachable.
When I try to reach the instance with generated load balancer DNS and port 9200 it is trying to connect for a couple of minutes. And then it says 'This site can't be reached' <DNS> took to long to response

**Steps to Reproduce**
1. Setup VPS with public Subnentw in availability zones us-west-2a, us-west-2b
2. Create AMI with Packer
3. Apply Terraform configuration
`
provider "aws" {
  region = "us-west-2"

  version = "~> 1.60"
}

provider "template" {
  version = "~> 2.1"
}

module "elasticsearch-prod-a" {
  source = "github.com/pelias/terraform-elasticsearch?ref=v7.3.0" # check Github for the latest tagged releases

  aws_vpc_id   = "vpc-`my-vpc`" # the ID of an existing VPC in which to create the instances
  ssh_key_name = "elasticsearch"

  aws_region                        = "us-west-2"
  subnet_name_filter                = "public-pelias-terraform-1"
  environment                       = "dev" # or whatever unique environment you choose
  elasticsearch_max_instances       = 2 # 2 r5.large instances is suitable for a minimal full-planet production build with replicas
  elasticsearch_min_instances       = 1
  elasticsearch_desired_instances   = 1
  elasticsearch_data_volume_size    = 350
  elasticsearch_instance_type       = "r5.large"
  elasticsearch_heap_memory_percent = 50
  ssh_ip_range                      = "`my-ip-range`" # adjust this if you'd like SSH access to be limited, or remove if you don't want that
  availability_zones                = "us-west-2b,us-west-2a"

  tags {
    env = "dev"
  }
}
`
4. Try to make a GET request

**Expected behavior**
I expect that instance will be available at load balancer DNS with port 9200. As it is with a regular elastic search module.

**Environment (please complete the following information):**
I have Mac
Terraform version 0.11.14

**Comment by missinglink** [comment]
I'm not the best person to ask about this, but is this line correct?

```
aws_vpc_id = "vpc-" # the ID of an existing VPC in which to create the instances
```

**Comment by KristinaHus** [comment]
Sorry, yes in real life it has a valid VPC id, I just removed it for security purpose.

**Comment by KristinaHus** [comment]
Or, are there any instructions on how to set up a pure elasticsearch container to work with Pelias?

**Comment by missinglink** [comment]
- https://github.com/pelias/docker/tree/master/images/elasticsearch/7.5.1
- https://github.com/pelias/packer-elasticsearch

**Comment by KristinaHus** [comment]
Thanks for these links!
But I'm creating AMI with this https://github.com/pelias/packer-elasticsearch configuration. And it is the one that is not working for me.

https://github.com/pelias/docker/tree/master/images/elasticsearch/7.5.1 - this is not exactly what I expected to get. Or I'm not sure how I can implement it with Terraform configuration. 

As I understand terraform-elasticsearch repository uses Elasticsearch with some additional configurations in setup.sh file, which is not working now. 
I'm trying to use another Elasticsearch image https://github.com/BigDataBoutique/elasticsearch-cloud-deploy and my Pelias container connects to it, but, as I understand, it is missing some configurations to work properly with Pelias. I'm wondering if someone can help me to configure this Elasticsearch instance to work with the Pelias container.

**Comment by KristinaHus** [comment]
If someone will need it. I was able to make it work by Migrating Load Balancer to Application Load Balancer with the internet-facing schema.
But after that, I had a problem with indexes, so I had to set it manually.
