### ISSUE TITLE
EntityAlreadyExists error

### ISSUE THREAD

**Issue by higorduarte98** [pelias/terraform-elasticsearch#23]
**Description**
When I run the terraform apply command I get the EntityAlreadyExists error for IAM Roles and Security Groups

**Steps to reproduce the behavior**
1. terraform init
2. terraform apply

**Environment**
 - OS: Ubuntu 20.04
 - Terraform: 0.11

**Aditional comments**
If i run "terraform apply -target=module.elasticsearch-prod-a" it work.

**Screenshots**
![image](https://user-images.githubusercontent.com/28016340/126159990-bcd8bab5-a536-465d-ab1c-af624d5a36dd.png)

**Comment by orangejulius** [comment]
Hi @higorduarte98,

Have you, or someone else, run `terraform apply` with the same `environment` module parameter?

If not, we've noticed that sometimes cleaning up with `terraform destroy` or similar leaves things behind. If you are 100% sure the existing IAM role or security group are not in use, its ok to delete them.

**Comment by higorduarte98** [comment]
> Hi @higorduarte98,
> 
> Have you, or someone else, run `terraform apply` with the same `environment` module parameter?
> 
> If not, we've noticed that sometimes cleaning up with `terraform destroy` or similar leaves things behind. If you are 100% sure the existing IAM role or security group are not in use, its ok to delete them.

Only I have access to the aws account. I'm sure no one has performed a terraform apply. In addition to performing terraform destroy, I checked if the terraform had deleted everything and there was. For some reason the terraform tries to add an already created resource.

![image](https://user-images.githubusercontent.com/28016340/126188783-5bd8e760-1ade-4214-8736-7ae26b74c3e3.png)

**Comment by orangejulius** [comment]
It looks like you are trying to set up multiple copies of Elasticsearch, which is supported, but the `environment` module parameter isn't changed. Looks like you have both a `prod` and `dev`, but they are both trying to create security groups called `pelias-dev-elasticsearch_elb`.

**Comment by higorduarte98** [comment]
> It looks like you are trying to set up multiple copies of Elasticsearch, which is supported, but the `environment` module parameter isn't changed. Looks like you have both a `prod` and `dev`, but they are both trying to create security groups called `pelias-dev-elasticsearch_elb`.

I just tested a setup, and it worked. But he created two environments, dev and prod, if I try to create only one environment, I get an error.
### elasticsearch.tf

![image](https://user-images.githubusercontent.com/28016340/126205952-d80ee0a2-d063-4d96-8fbe-ca87d8abb8bc.png)

### variables.tf

![image](https://user-images.githubusercontent.com/28016340/126205999-67c15f5d-c4e9-4810-b211-cd8f6c7c1ae6.png)

### launch_configuration.tf

![image](https://user-images.githubusercontent.com/28016340/126206200-350e2b20-b02b-412d-8751-a37db17aeaa4.png)

**Comment by higorduarte98** [comment]
I made a mistake which was to download the git repository and add the elasticsearch.tf file to the root directory. Now I understand that I didn't need to download the repository, just create the elasticsearch.tf file.

**Comment by orangejulius** [comment]
Thanks for following up @higorduarte98, thank makes sense. Actually I think I made that same mistake at some point when originally developing this module a few years ago 😆

Terraform and HCL syntax are definitely a bit tricky, I wonder if there's a way we can prevent this problem by marking the code in here as "must be run as a submodule, not a root-module" in some way. If you or anyone else knows we'd love to hear about it.
